- name: play level variables
  hosts: local
  connection: local
  vars:
     COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
     DURATION: 10HR
     TRAINER: Ramesh
  tasks:
  - name: print course informantion
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello ansible, Course duration: 10HR, Trainer is ramesh"

  - name: print course informantion again
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
      

