- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    Duration: 120 # This is number
    COURSE: "DevSecOps with AWS" # String
    IS_LIVE: true # bollean
    TOOLS: # List []
    - Linux
    - shell
    - Ansible
    CONCEPTS: # map or dictionary or object. referred like {}
      CI: Jenkins
      SCRIPTING: "shell, Ansible, Terraform, Python"
  tasks:
  - name: print course informantion
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE}}, DURATION is: {{DURATION}}, is live?: {{ IS_LIVE }}, 
            Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS}}"
      