- name: functions
  hosts: local
  connection: local
  var:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ Persons | split(',')}}"

